# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.require_version ">= 1.8.1"

Vagrant.configure(2) do |config|

 config.vm.define "default", autostart: false do |default|
   default.vm.hostname = "webui-dev"
   default.vm.box = "bubuplanet/cirrusos"
   default.vm.box_url = "https://atlas.hashicorp.com/bubuplanet/boxes/cirrusos"
   default.vm.box_check_update = true
   # default.vm.network "forwarded_port", guest: 80, host: 10081
   default.vm.network "private_network", ip: "192.168.82.101"
   # default.vm.network "public_network"
   # default.vm.synced_folder "cirrus/module/", "/home/vagrant/", create: true, owner: "root", group: "root"
   
   default.vm.provider "virtualbox" do |vb|
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
   end

 end

 config.vm.define "app" do |app|
   app.vm.provider "docker" do |docker|
     docker.image = "debian"
     docker.volumes = %w(/var/www:/var/www)
     docker.name = "app"
     docker.vagrant_vagrantfile = __FILE__
     docker.remains_running = false
   end
 end

 config.vm.define "nginx" do |nginx|
   nginx.vm.provider "docker" do |docker|
    docker.vagrant_vagrantfile = __FILE__ 
    docker.image = "nginx"
    docker.create_args = %w(--volumes-from="app")
    docker.ports = %w(80:10081)	
   end
 end

end
