# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.require_version ">= 1.8.1"

Vagrant.configure(2) do |config|

 config.vm.define "default", autostart: false do |default|
   default.vm.hostname = "webui-dev"
   default.vm.box = "bubuplanet/cirrusos"
   default.vm.box_url = "https://atlas.hashicorp.com/bubuplanet/boxes/cirrusos"
   default.vm.box_check_update = true
   default.vm.network "private_network", ip: "192.168.82.101"
   default.vm.synced_folder "app/www", "/var/www", create: true 
   
   default.vm.provider "virtualbox" do |vb|
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
   end

 end

 #
 # Run Apache2 in Docker "vagrant up apache2"
 #
 config.vm.define "apache2", autostart: false do |httpd|
    httpd.vm.provider "docker" do |docker|
      docker.build_dir = "environment/docker/config/httpd"
      docker.volumes = ["/var/www:/usr/local/apache2/htdocs/"]
      docker.ports = ["10180:80"]
      docker.vagrant_vagrantfile = __FILE__
    end
 end

 #
 # Run NGINX in the Docker "vagrant up nginx"
 #
 config.vm.define "nginx" do |nginx|
   nginx.vm.provider "docker" do |docker|
    docker.build_dir = "environment/docker/config/nginx"
    docker.volumes = ["/var/www:/usr/share/nginx/html"]
    docker.ports = ["10181:80"]	
    docker.vagrant_vagrantfile = __FILE__
   end
 end

end
