# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.require_version ">= 1.8.1"

Vagrant.configure(2) do |config|
  # Change the hostname of this vagrant file to match the name of the module
  # that your are developing
  config.vm.hostname = "vagrant-api-dev"

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "bubuplanet/cirrusos"

  config.vm.box_url = "https://atlas.hashicorp.com/bubuplanet/boxes/centos7-minimal"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = true

  # Create a forwardded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 80, host: 10080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.82.100"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "cirrus/module/", "/home/vagrant/", create: true, owner: "root", group: "root"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.

  config.vm.provider "virtualbox" do |vb|
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
  end

  # config.ssh.port = 22

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.

  config.vm.provision "shell", inline: <<-SHELL
     echo "Running update command for Centos 'yum -y update'"
     sudo yum -y -q update

     echo "Installing EPEL repository required for nodejs installtion"
     sudo yum -y -q install epel-release

     echo "Installing nodejs 'yum -y install nodejs'"
     sudo yum -y -q install nodejs

     echo "Installing npm 'yum -y install npm'"
     sudo yum -y -q install npm

     echo "Installing Git 'yum -y install git'"
     sudo yum -y -q install git

     echo "Versions installed"
     sudo git --version
     sudo node -v
     sudo npm -v

     echo "Installing winston@2.2.0 and winston-elasticsearch@0.2.6 for nodejs to use as the logging provider"
     sudo npm install -g winston@2.2.0 winston-elasticsearch@0.2.6 --loglevel silent

     echo "Installing apidoc to generate the required Documentation"
     sudo npm install -g apidoc@0.15.1 --loglevel silent

  SHELL

end
