# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.require_version ">= 1.8.1"

Vagrant.configure(2) do |config|

 config.vm.define "default", autostart: false do |default|
   default.vm.hostname = "loggingserver"
   default.vm.box = "bubuplanet/cirrusos"
   default.vm.box_url = "https://atlas.hashicorp.com/bubuplanet/boxes/cirrusos"
   default.vm.box_check_update = true
   default.vm.network "private_network", ip: "192.168.82.102"
   default.vm.synced_folder ".", "/vagrant", create: false
   default.vm.synced_folder ".", "/vagrant/elasticsearch", create: true
 
   default.vm.provider "virtualbox" do |vb|
     # Customize the amount of memory on the VM:
     vb.memory = "2048"
     vb.name = "LoggingServer"
   end

   default.vm.provision "docker" do |docker|
     docker.build_image "/vagrant/environment/docker/config/elk", args: "-t vagrantdocker/elasticsearch"
     docker.build_image "/vagrant/environment/docker/config/kibana", args: "-t vagrantdocker/kibana"
     docker.build_image "/vagrant/environment/docker/config/logstash", args: "-t vagrantdocker/logstash"
   end

 end


 # RUN: vagrant up --no-parallel
 
 #
 # Elasticsearch 
 #
 config.vm.define "elasticsearch", autostart: true do |e|
    e.vm.provider "docker" do |docker|
      docker.image = "vagrantdocker/elasticsearch"
      docker.name = "elasticsearch"
      docker.volumes = ["/vagrant/elasticsearch:/usr/share/elasticsearch/data"]
      docker.ports = ["9200:9200","9300:9300"]
      docker.vagrant_vagrantfile = __FILE__
    end
 end

 #
 # Kibana 
 #
 config.vm.define "kibana", autostart: true do |kibana|
   kibana.vm.provider "docker" do |docker|
    docker.image = "vagrantdocker/kibana"
    docker.name = "kibana"
    docker.ports = ["5601:5601"]
    #docker.link "elasticserach:elasticserach"
    docker.create_args = %w(-e ELASTICSEARCH_URL=http://192.168.82.102:9200)
    docker.vagrant_vagrantfile = __FILE__
   end
 end

 #
 # Logstash
 #
 config.vm.define "logstash", autostart: true do |l|
    l.vm.provider "docker" do |docker|
      docker.image = "logstash:2.3.1"
      docker.name = "logstash"
      docker.create_args = %w(-it -v /vagrant:/config-dir logstash -f /config-dir/logstash.conf --verbose --auto-reload)
      docker.ports = ["9997:9997","9998:9998","9999:9999"]
      docker.vagrant_vagrantfile = __FILE__
    end
 end

end
