# -*- mode: ruby -*-
# vi: set ft=ruby :
# Avoid having to pass --provider=docker
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
Vagrant.configure("2") do |config|
  # Start Provision
  config.vm.define "apache" do |a|
    # Tell Vagrant to use Docker
    a.vm.provider "docker" do |d|
      # Pull the apache httpd container from the docker hub
      d.image = "httpd"
      # Tell Docker to name the container 'apache'
      d.name = "apache"
      # Assign ports 80 and 443 to the container
      d.ports = ["80:80", "433:443"]
      # Make sure the container stays running when started
      d.remains_running = true
      # Use the HostVagrantfile settings to provision
      d.vagrant_vagrantfile = "HostVagrantfile"
    end
  end
end
