# -*- mode: ruby -*-
# vi: set ft=ruby :


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.require_version ">= 1.8.1"

Vagrant.configure(2) do |config|

  config.vm.define "default", autostart: true do |default|
    default.vm.hostname = "mongo"
    default.vm.box = "bubuplanet/cirrusos"
    default.vm.box_url = "https://atlas.hashicorp.com/bubuplanet/boxes/cirrusos"
    default.vm.box_check_update = true
    default.vm.network "private_network", ip: "192.168.82.104"
    default.vm.synced_folder ".", "/vagrant", create: true

    default.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
    end

    default.vm.provision "docker" do |docker|
      docker.build_image "/vagrant/environment/docker/config/mongo", args: '-t "cirrusmongo"'
    end

  end
  #
  # Run mongo in Docker
  #
  config.vm.define "mongo", autostart: true do |db|
    db.vm.provider "docker" do |docker|
      docker.image = "mongo"
      docker.name = "mongo"
      docker.volumes = ["/vagrant:/data"]
      docker.ports = ["27017:27017"]
      docker.vagrant_vagrantfile = __FILE__
    end
  end
  #
  # Run mongo-express in Docker
  #
  config.vm.define "mongo-express", autostart: true do |db|
    db.vm.provider "docker" do |docker|
      docker.image = "mongo-express"
      docker.name = "mongo-express"
      docker.link("mongo:mongo")
      docker.ports = ["8081:8081"]
      docker.vagrant_vagrantfile = __FILE__
    end
  end

end
